services:
  - type: web
    name: leetcode-tracker
    runtime: docker
    plan: free
    region: ohio
    envVars:
      - key: MONGO_URI
        description: "MongoDB Atlas Connection String"
        sync: false
      - key: MONGO_DB
        description: "The name of the database"
        value: "LeetcodeTracker"
      - key: REDIS_HOST
        fromService:
          name: leetcode-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: leetcode-redis
          type: redis
          property: port
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

  - type: redis
    name: leetcode-redis
    plan: free
    region: ohio
    ipAllowList: [] # Only allow internal traffic from the backend
